<% require 'methodology_toolkit/db/configuration' %>

storefront_common: &storefront_common
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['POSTGRES_HOST'].presence || 'localhost' %>
  username: <%= ENV['POSTGRES_USERNAME'].presence || ENV['DATABASE_USERNAME'].presence || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'].presence || ENV['DATABASE_PASSWORD'].presence || 'password' %>
  pool: <%= ENV['DB_POOL'].presence || 5 %>

development:
  <<: *storefront_common
  database: <%= MethodologyToolkit::DB::Configuration.development_db('storefront') %>

test: &test
  <<: *storefront_common
  database: <%= MethodologyToolkit::DB::Configuration.test_db('storefront') %>

production:
  <<: *storefront_common
  database: storefront_production
